windows-terminal/flexoki.json, windows-terminal/instructions.md
Screenshot of the preview pane:
=> Add Windows terminal theme file

kitty/flexoki_dark.conf, kitty/flexoki_light.conf
I added a light and dark color scheme for the kitty terminal. Love this color scheme!
=> Add Kitty terminal color schemes

kitty/flexoki_dark.conf, kitty/flexoki_light.conf
Adjusted black and white values in the colors schemes to be consistent with documentation.
Also adjusted formatting in light color scheme
=> Fix inconsistencies in Kitty colors

README.md, alacritty/flexoki.yaml
This PR adds a port for [Alacritty](https://alacritty.org/).
=> Alacritty Port

Xresources/flexoki-dark, Xresources/flexoki-light
Resource names were merged from some other themes.  Saw the theme on HN and immediately wanted it on everything!
=> Added Xresources

warp-terminal/flexoki-dark.yaml, warp-terminal/flexoki-light.yaml
https://www.warp.dev
Creating after following this documentation https://docs.warp.dev/appearance/custom-themes
=> Add warp terminal light and dark themes

wezterm/Flexoki Light.toml
Hey I like the theme! I noticed there was an issue with the wezterm light theme.
=> Fix Flexoki Light for wezterm.

wezterm/Flexoki Dark.toml
=> Update Flexoki Dark.toml

README.md, slack/slack.md
Adds custom theme definitions for light and dark mode in Slack.
=> Adds Slack theme

fish/flexoki-dark.theme, fish/flexoki-light.theme
https://fishshell.com/
First time contrubuting to OSS so correct me if I've done something wrong.
=> Add fish port

waybar/README.md, waybar/flexoki-dark.css, waybar/flexoki-full.css, waybar/flexoki-light.css
https://github.com/Alexays/Waybar/
||ugh, I need to be more careful when working with git and remember to change branches as reverting changes and removing commits here can be tricky with my bad habit of add files-commit-immediately push||
=> Add waybar port

i3/README.md, i3/flexoki-dark.css, i3/flexoki-full.css, i3/flexoki-light.css
https://i3wm.org/
https://swaywm.org/
=> Add i3/sway port

i3/README.md, i3/flexoki-dark.css, i3/flexoki-full.css, i3/flexoki-light.css, tealdeer/README.md, tealdeer/flexoki-dark.toml, tealdeer/flexoki-light.toml
https://github.com/dbrgn/tealdeer
=> Add tealdeer port

dunst/README.md, dunst/flexoki-dark.conf, dunst/flexoki-light.conf
=> Add dunst support

wezterm/Flexoki Dark.toml
While putting the webpage up against the terminal I noticed the colors were off. The colors matched the hex but not the rgb (which is confusing).
=> Update Flexoki Dark.toml to Hex

README.md, tape/flexoki_dark.svg, tape/flexoki_light.svg
Added a port for [Tape](https://aeriform.itch.io/tape).
=> Add Tape port

README.md
lmk if i should move it to a different section
=> Add Wikipedia CSS Theme

README.md
Add Flexoki theme for NetNewsWire, an RSS reader to README.
=> Add NewNewsWire to README

tmux/flexoki-dark.tmuxtheme, tmux/flexoki-light.tmuxtheme
Instead of only suppplying the colours, apply them to tmux as well. These changes have been found in the original author's, @tklai, dotfile repository.
Resolves #89
=> fix(tmux): apply colourscheme to tmux

fzf/README.md, kitty/flexoki_dark.conf
also added fish instruction for fzf
=> foreground color fix in fzf and kitty 

README.md
[Yazi](https://github.com/sxyazi/yazi) is a terminal file manager
=> Add Yazi port

README.md
Add link to Flexoki Extended Palette color set for Clip Studio Paint.
=> Update README.md with link to Clip Studio Paint color set

xcode/Flexoki Dark.xccolortheme, xcode/Flexoki Light.xccolortheme, xcode/README.md
=> feat: adds xcode port

README.md, zellij/README.md, zellij/flexoki.kdl
- Add Flexoki theme for [Zellij](https://zellij.dev/)
- Includes both light and dark variants
=> Add Zellij port
